/*
 * english-mastery · 单词巧记（WORD_TRICKS）
 * 给单词配一条「巧记法」，帮孩子用联想 / 谐音 / 拆分 / 对比 / 故事 记住难词、易混词。
 *
 * 字段：
 *   word   : 英文单词（小写规范）
 *   zh     : 中文释义
 *   trick  : 巧记法说明（中文，口语化、给孩子看的）
 *   method : 方法类型 —— 联想 / 谐音 / 拆分 / 对比 / 故事
 *   grade  : 适用学段 —— all(通用) / primary(小学) / junior(初中) / senior(高中)
 *
 * ⚠️ 数据性质：本文件是「核心种子巧记」，覆盖高频易混词，并非全量。
 *   孩子自己想出来的口诀更有用 —— 在 App 内「💡 单词巧记 → ➕ 添加我的巧记」里补充，
 *   存 localStorage，永不丢失，也跟着单文件版一起离线可用。
 */
window.WORD_TRICKS = [
  /* ---------- 谐音法：读音像中文，直接挂钩 ---------- */
  { word: "ambulance", zh: "救护车", method: "谐音", grade: "all", trick: "谐音「俺不能死」→ 赶紧叫救护车。" },
  { word: "pest", zh: "害虫；讨厌的人", method: "谐音", grade: "all", trick: "谐音「拍死它」→ 害虫拍死它。" },
  { word: "ambition", zh: "雄心；志向", method: "谐音", grade: "senior", trick: "谐音「俺必胜」→ 有「俺必胜」的劲头就是 ambition。" },
  { word: "candidate", zh: "候选人", method: "谐音", grade: "senior", trick: "谐音「看的是他」→ 候选人就是大家「看的是他」。" },
  { word: "famine", zh: "饥荒", method: "谐音", grade: "senior", trick: "谐音「发米呢」→ 饥荒时盼着「发米呢」。" },
  { word: "poem", zh: "诗", method: "谐音", grade: "primary", trick: "谐音「泼墨」→ 泼墨写诗。" },
  { word: "tomb", zh: "坟墓", method: "谐音", grade: "junior", trick: "谐音「土墓」→ 土里挖的墓。" },
  { word: "panda", zh: "熊猫", method: "谐音", grade: "primary", trick: "谐音「盼大」→ 盼着它长大，国宝熊猫。" },

  /* ---------- 拆分法：把长词拆成熟悉的小块 ---------- */
  { word: "because", zh: "因为", method: "拆分", grade: "primary", trick: "be(是)+ cause(原因)= 是……的原因 → 因为。" },
  { word: "broadcast", zh: "广播；播送", method: "拆分", grade: "junior", trick: "broad(宽广的)+ cast(投、撒)= 撒向宽广处 → 广播。" },
  { word: "classmate", zh: "同学", method: "拆分", grade: "primary", trick: "class(班级)+ mate(伙伴)= 班里的伙伴 → 同学。" },
  { word: "birthday", zh: "生日", method: "拆分", grade: "primary", trick: "birth(出生)+ day(日子)= 出生那天 → 生日。" },
  { word: "bathroom", zh: "浴室", method: "拆分", grade: "primary", trick: "bath(洗澡)+ room(房间)= 洗澡的房间 → 浴室。" },
  { word: "bedroom", zh: "卧室", method: "拆分", grade: "primary", trick: "bed(床)+ room(房间)= 放床的房间 → 卧室。" },
  { word: "football", zh: "足球", method: "拆分", grade: "primary", trick: "foot(脚)+ ball(球)= 用脚踢的球 → 足球。" },
  { word: "classroom", zh: "教室", method: "拆分", grade: "primary", trick: "class(课)+ room(房间)= 上课的房间 → 教室。" },
  { word: "homework", zh: "家庭作业", method: "拆分", grade: "primary", trick: "home(家)+ work(工作)= 在家做的工作 → 作业。" },
  { word: "bedtime", zh: "就寝时间", method: "拆分", grade: "primary", trick: "bed(床)+ time(时间)= 上床的时间 → 睡觉时间。" },
  { word: "blackboard", zh: "黑板", method: "拆分", grade: "primary", trick: "black(黑)+ board(板)= 黑色的板 → 黑板。" },
  { word: "sunshine", zh: "阳光", method: "拆分", grade: "primary", trick: "sun(太阳)+ shine(照耀)= 太阳照耀 → 阳光。" },
  { word: "watermelon", zh: "西瓜", method: "拆分", grade: "primary", trick: "water(水)+ melon(瓜)= 水多的瓜 → 西瓜。" },
  { word: "strawberry", zh: "草莓", method: "拆分", grade: "primary", trick: "straw(稻草)+ berry(莓)= 像躺在稻草上的莓 → 草莓。" },
  { word: "grandmother", zh: "奶奶；外婆", method: "拆分", grade: "primary", trick: "grand(大的)+ mother(妈妈)= 大妈妈 → 奶奶/外婆。" },
  { word: "grandfather", zh: "爷爷；外公", method: "拆分", grade: "primary", trick: "grand(大的)+ father(爸爸)= 大爸爸 → 爷爷/外公。" },
  { word: "fireman", zh: "消防员", method: "拆分", grade: "primary", trick: "fire(火)+ man(人)= 灭火的人 → 消防员。" },
  { word: "postman", zh: "邮递员", method: "拆分", grade: "junior", trick: "post(邮政)+ man(人)= 送信的人 → 邮递员。" },
  { word: "fisherman", zh: "渔夫", method: "拆分", grade: "junior", trick: "fish(鱼)+ er + man(人)= 打鱼的人 → 渔夫。" },
  { word: "business", zh: "生意；商业", method: "拆分", grade: "junior", trick: "bus(公车)+ in + ess → 想象「公车里的人在做生意」。" },
  { word: "vegetable", zh: "蔬菜", method: "拆分", grade: "primary", trick: "vege(像「喂鸡」)+ table(桌)= 桌上喂鸡的菜 → 蔬菜。" },
  { word: "Wednesday", zh: "星期三", method: "拆分", grade: "primary", trick: "Wed(结婚的「韦」)+ nes + day → 记「星期三 Wed」别拼错。" },
  { word: "knowledge", zh: "知识", method: "拆分", grade: "junior", trick: "know(知道)+ ledge(像「ledge 壁架」) → 知道的都摆上架 = 知识。" },
  { word: "mountain", zh: "山", method: "拆分", grade: "primary", trick: "mount(爬)+ ain → 要爬的「ain」就是山；mountain 里有「tain」像「tain 山」。" },
  { word: "underground", zh: "地铁；地下的", method: "拆分", grade: "primary", trick: "under(在…下)+ ground(地面)= 地面之下 → 地铁/地下。" },
  { word: "toothache", zh: "牙痛", method: "拆分", grade: "primary", trick: "tooth(牙)+ ache(痛)= 牙 + 痛 → 牙痛。" },
  { word: "headache", zh: "头痛", method: "拆分", grade: "primary", trick: "head(头)+ ache(痛)= 头 + 痛 → 头痛。" },
  { word: "playground", zh: "操场；游乐场", method: "拆分", grade: "primary", trick: "play(玩)+ ground(场地)= 玩的场地 → 操场。" },
  { word: "breakfast", zh: "早餐", method: "拆分", grade: "primary", trick: "break(打破)+ fast( fasting 禁食)= 打破禁食的第一餐 → 早餐。" },
  { word: "grandparent", zh: "祖父母", method: "拆分", grade: "primary", trick: "grand(大的)+ parent(父母)= 父母的父母 → 祖父母。" },
  { word: "notebook", zh: "笔记本", method: "拆分", grade: "junior", trick: "note(笔记)+ book(本)= 记笔记的本 → 笔记本。" },

  /* ---------- 联想法：画面 / 故事挂勾 ---------- */
  { word: "island", zh: "岛", method: "联想", grade: "junior", trick: "is(是)+ land(陆地)= 它「是」一块水中的陆地 → 岛。（s 不发音，别写成 iland）" },
  { word: "friend", zh: "朋友", method: "联想", grade: "primary", trick: "friend 中间藏着一个 lie(谎言)？不——记住「朋友之间不说谎」反而好记；也记 fri + end = 友谊到 end 仍在。" },
  { word: "believe", zh: "相信", method: "联想", grade: "junior", trick: "中间有个 lie(谎言)，但 believe 整体是「看穿谎言才真相信」；注意是 ie 不是 ei。" },
  { word: "peasant", zh: "农民", method: "联想", grade: "junior", trick: "pea(豌豆)+ sant(像「圣」) → 种豌豆的圣农 → 农民。" },
  { word: "quiet", zh: "安静的", method: "联想", grade: "primary", trick: "qui(像「亏」)+ et → 吵闹会「吃亏」，所以要 quiet 安静。" },
  { word: "quite", zh: "相当；十分", method: "对比", grade: "primary", trick: "和 quiet 只有 e/i 之差：quiet 多一个 e 更「安逸(quiet)」，quite 是「相当」。e 在尾= 相当(quite)。" },
  { word: "weather", zh: "天气", method: "对比", grade: "primary", trick: "weather(天气) vs whether(是否)：天气 weather 跟「水/雨」有关，多一个 a；whether 是「是否」。" },
  { word: "whether", zh: "是否", method: "对比", grade: "junior", trick: "whether(是否) vs weather(天气)：whether 没有 a，问的是「是否」不是「天气」。" },
  { word: "their", zh: "他们的", method: "对比", grade: "primary", trick: "their(他们的，带 heir 像「继承」) / there(那里，有 here 的 e) / they're(他们是，=they are)。" },
  { word: "there", zh: "那里", method: "对比", grade: "primary", trick: "there(那里) 里含 here(这里) 的 e → 那里是「这里」的远处。" },
  { word: "they're", zh: "他们是", method: "对比", grade: "junior", trick: "they're = they are，带撇号；their 是所有格「他们的」。" },
  { word: "its", zh: "它的", method: "对比", grade: "primary", trick: "its(它的，无撇) vs it's(它是 = it is，有撇)。名词性所有格无撇，缩写有撇。" },
  { word: "it's", zh: "它是", method: "对比", grade: "primary", trick: "it's = it is，带撇号；its 是所有格「它的」无撇。" },
  { word: "your", zh: "你的", method: "对比", grade: "primary", trick: "your(你的，无撇) vs you're(你是 = you are，有撇)。" },
  { word: "you're", zh: "你是", method: "对比", grade: "junior", trick: "you're = you are，带撇；your 是「你的」无撇。" },
  { word: "whose", zh: "谁的", method: "对比", grade: "primary", trick: "whose(谁的，无撇) vs who's(谁是 = who is，有撇)。" },
  { word: "accept", zh: "接受", method: "对比", grade: "junior", trick: "accept(接受，两 c 两 p) vs except(除了，一 c 一 p 且 ex 开头)。" },
  { word: "except", zh: "除了", method: "对比", grade: "junior", trick: "except(除了) 以 ex 开头；accept(接受) 以 ac 开头。ex=向外(排除)，ac=朝(接纳)。" },
  { word: "affect", zh: "影响(动词)", method: "对比", grade: "junior", trick: "affect(影响，动词，a 在前) vs effect(效果/影响，名词，e 开头；也可作动词「实现」)。" },
  { word: "effect", zh: "效果；影响(名词)", method: "对比", grade: "junior", trick: "effect 名词「效果」；affect 动词「影响」。口诀：A 是动作(affect)，E 是结果(effect)。" },
  { word: "principle", zh: "原则", method: "对比", grade: "junior", trick: "principle(原则，结尾 -le) vs principal(校长/主要的，结尾 -al)。校长 principal 是「第一(al)人」。" },
  { word: "principal", zh: "校长；主要的", method: "对比", grade: "junior", trick: "principal(校长/主要的) 结尾 -al；principle(原则) 结尾 -le。校长是学校的「主要(al)」人。" },
  { word: "stationery", zh: "文具", method: "对比", grade: "junior", trick: "stationery(文具，有 e) vs stationary(静止的，无 e)。文具店「有货(e)」，静止「没动」。" },
  { word: "stationary", zh: "静止的", method: "对比", grade: "junior", trick: "stationary(静止的，无 e) vs stationery(文具，有 e)。静止的东西「不动」。" },
  { word: "advise", zh: "建议(动词)", method: "对比", grade: "junior", trick: "advise(动词建议，s) vs advice(名词建议，c)。动词用 s(像 say)，名词用 c。" },
  { word: "advice", zh: "建议(名词)", method: "对比", grade: "junior", trick: "advice(名词建议，c) vs advise(动词建议，s)。名词 c，动词 s。" },
  { word: "through", zh: "穿过；通过", method: "对比", grade: "primary", trick: "through(穿过，ough) / though(虽然，o) / thought(思想，au) / thorough(彻底的，oro)。through 是「一路穿过去」。" },
  { word: "dessert", zh: "甜点", method: "联想", grade: "primary", trick: "dessert(甜点) 有两个 s —— 想吃「双份(s)」甜点；desert(沙漠) 只有一个 s。" },
  { word: "desert", zh: "沙漠；抛弃", method: "对比", grade: "junior", trick: "desert(沙漠/抛弃) 单 s；dessert(甜点) 双 s。沙漠里没甜点，所以单 s。" },
  { word: "loose", zh: "松的；宽松的", method: "对比", grade: "junior", trick: "loose(松的，双 o) vs lose(丢失，单 o)。东西太「松(loose)」就容易「丢(lose)」。" },
  { word: "lose", zh: "丢失", method: "对比", grade: "primary", trick: "lose(丢失，单 o) vs loose(松的，双 o)。丢(lose) 了东西很糟，只有一个 o。" },
  { word: "than", zh: "比", method: "对比", grade: "primary", trick: "than(比) vs then(然后)。比(than) 完才「然后(then)」。" },
  { word: "then", zh: "然后", method: "对比", grade: "primary", trick: "then(然后) vs than(比)。先比(than)再然后(then)。" },
  { word: "break", zh: "打破；休息", method: "对比", grade: "primary", trick: "break(打破/休息) vs brake(刹车)。刹车 brake 多了个 a，像「闸」。" },
  { word: "brake", zh: "刹车", method: "对比", grade: "junior", trick: "brake(刹车) vs break(打破)。刹车要「a」一下才停。" },
  { word: "hear", zh: "听见", method: "对比", grade: "primary", trick: "hear(听见，ear 耳朵) vs here(这里)。用 ear(耳朵) 才能 hear(听见)。" },
  { word: "here", zh: "这里", method: "对比", grade: "primary", trick: "here(这里) 含 e；hear(听见) 含 ear(耳朵)。" },
  { word: "two", zh: "二", method: "对比", grade: "primary", trick: "two(二，w 像 2) / too(也/太，同音) / to(去，介词)。w 像 2 → two。" },
  { word: "see", zh: "看见", method: "对比", grade: "primary", trick: "see(看见，ee 像两只眼) vs sea(海，同音)。两只眼 ee 才能 see。" },
  { word: "sea", zh: "海", method: "对比", grade: "primary", trick: "sea(海，同音 see) vs see(看见)。" },
  { word: "four", zh: "四", method: "对比", grade: "primary", trick: "four(四) vs for(为了)。四 four 有 u，像「four」= 4。" },
  { word: "write", zh: "写", method: "对比", grade: "primary", trick: "write(写，w 开头) vs right(对的/右边，无 w)。写 write 用右手(right)。" },
  { word: "right", zh: "对的；右边", method: "对比", grade: "primary", trick: "right(对的/右边) vs write(写)。右手(right) 拿笔 write。" },
  { word: "our", zh: "我们的", method: "对比", grade: "primary", trick: "our(我们的) vs hour(小时，多了 h)。一小时 hour 很长。" },
  { word: "hour", zh: "小时", method: "对比", grade: "junior", trick: "hour(小时，h 在首，不发音) vs our(我们的)。hour 多一个 h。" },
  { word: "meat", zh: "肉", method: "对比", grade: "primary", trick: "meat(肉，ea) / meet(遇见，ee) / mete(分配) 同音。吃 meat 长肉。" },
  { word: "meet", zh: "遇见", method: "对比", grade: "primary", trick: "meet(遇见，ee) vs meat(肉，ea)。遇见 meet 用两个 e。" },
  { word: "peace", zh: "和平", method: "对比", grade: "junior", trick: "peace(和平，ea) vs piece(一块/片，ie)。和平 peace 用 ea。" },
  { word: "piece", zh: "一片；一块", method: "对比", grade: "junior", trick: "piece(一片，ie) vs peace(和平，ea)。一块 piece 用 ie。" },
  { word: "son", zh: "儿子", method: "对比", grade: "primary", trick: "son(儿子) vs sun(太阳) 同音。儿子 son 像小太阳 sun。" },
  { word: "sun", zh: "太阳", method: "对比", grade: "primary", trick: "sun(太阳) vs son(儿子) 同音。" },
  { word: "one", zh: "一", method: "对比", grade: "primary", trick: "one(一，o 像 0/1 之间) vs won(赢，过去式) 同音。得「一(one)」分就赢(won)。" },
  { word: "won", zh: "赢(过去式)", method: "对比", grade: "junior", trick: "won(赢) vs one(一) 同音。" },
  { word: "eight", zh: "八", method: "联想", grade: "primary", trick: "eight(八) 里藏着 ht 像「8」的胖圈；注意有 gh 不发音。" },
  { word: "know", zh: "知道", method: "联想", grade: "primary", trick: "know(知道) 的 k 不发音，读「no」；no 就是「知道/不」。o 在尾像点头。" },
  { word: "knew", zh: "知道(过去式)", method: "对比", grade: "junior", trick: "knew(知道过去式) 同音 new(新的)。" },
  { word: "night", zh: "夜晚", method: "对比", grade: "primary", trick: "night(夜晚，gh 不发音) vs knight(骑士，k 不发音) 同音。夜晚 night 里藏着 igh。" },
  { word: "no smoking", zh: "禁止吸烟", method: "联想", grade: "primary", trick: "no(不)+ smoking(吸烟)= 不要吸烟 → 禁止吸烟。看到就停手。" },
  { word: "necessary", zh: "必要的", method: "联想", grade: "junior", trick: "记「一顶帽子(cola 式的 c)、两件上衣(两个 e)、一条裤子(一个 a)、一双袜子(两个 s)」，正好 1c2e1a2s → necessary。" },
  { word: "separate", zh: "分开；使分离", method: "联想", grade: "junior", trick: "中间藏着一个 rat(老鼠) → 把老鼠 separate(分开) 出去。" },
  { word: "beautiful", zh: "美丽的", method: "拆分", grade: "primary", trick: "beau(像「波」)+ ti + ful → 记「beau-ti-ful」三拍，别漏 ti。" },
  { word: "laugh", zh: "笑", method: "联想", grade: "primary", trick: "laugh(笑) 的 gh 不发音，读「拉夫」。笑(laugh) 时嘴巴张大 au。" },
  { word: "tongue", zh: "舌头", method: "联想", grade: "junior", trick: "tongue(舌头) 的 ue 不发音，读「糖」。舌头在嘴里像一块糖 tongue。" },
  { word: "minute", zh: "分钟", method: "联想", grade: "primary", trick: "minute(分钟) 的 u 不发音，读「米尼特」。一分钟 minute 很短。" },
  { word: "people", zh: "人们", method: "联想", grade: "primary", trick: "people(人们) 结尾 ple 像「普乐」→ 人们普乐。" },
  { word: "women", zh: "女人们", method: "对比", grade: "primary", trick: "women(女人们) 读作「威敏」；man→men、woman→women，复数是 e 变 a 的怪规律。" },
  { word: "children", zh: "孩子们", method: "联想", grade: "primary", trick: "child(孩子) 变复数加 ren 成 children(孩子们)，像「孩儿们」。" },
  { word: "could", zh: "能(过去式)", method: "对比", grade: "primary", trick: "could / would / should 都以 ould 结尾，读「库德/伍德/书的」。三个「老友」一组记。" },
  { word: "rhythm", zh: "节奏", method: "联想", grade: "senior", trick: "rhythm(节奏) 没有元音 a,e,i,o 只有 y 和 h，最难拼，记「rhy-thm」两截，h 不发音。" },
  { word: "island", zh: "岛", method: "故事", grade: "junior", trick: "「我(is)站在陆地(land)上，四面是水」→ 这就是 island 岛。（s 不发音）" },
  { word: "price", zh: "价格", method: "对比", grade: "junior", trick: "price(价格，i) vs prize(奖品，无 i) 同音。价格 price 里有个 i 像价签。" },
  { word: "prize", zh: "奖品", method: "对比", grade: "junior", trick: "prize(奖品) 无 i；price(价格) 有 i。奖品 prize 到手很开心。" },
  { word: "quiet", zh: "安静的", method: "故事", grade: "primary", trick: "小偷 qui 想偷 et，被「嘘——」(quiet 安静) 别出声。quiet = 安静。" },
  { word: "through", zh: "穿过", method: "故事", grade: "primary", trick: "小虫 thr 一路 ou 爬过 gh 山洞 → 穿 through 过去。" }
];
